# .github/workflows/compile-scout-latest-gcc.yml

name: Compile and Run Scout with Latest GCC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Latest GCC
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 50
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 50

    - name: Verify GCC Version
      run: gcc --version

    - name: Compile scout.cpp
      run: |
        g++ -o scout scout.cpp
        ./scout
