

# .github/workflows/compile-scout.yml

name: Compile and Run Scout

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get install -y g++

    - name: Compile scout.cpp
      run: |
        g++ -o scout scout.cpp
        ./scout

